"""Interchangeable abbreviation resolvers and prediction artifacts."""

from abrex.resolvers.adapters.ab3p import (
    AB3P_ADAPTER_VERSION,
    AB3P_OFFSET_SCHEMA_VERSION,
    AB3P_WRAPPER_VERSION,
    Ab3PCacheConfig,
    Ab3PInstallationConfig,
    Ab3PMappingError,
    Ab3PParseError,
    Ab3PResolverConfig,
    ParsedAbbreviation,
    build_ab3p_input,
    parse_ab3p_offset_output,
    parse_ab3p_output,
    reconstruct_offset_predictions,
    reconstruct_predictions,
)
from abrex.resolvers.adapters.ab3p_resolver import Ab3PResolver
from abrex.resolvers.adapters.bioadi import (
    BIOADI_ADAPTER_VERSION,
    BioADIMappingError,
    BioADIPair,
    BioADIParseError,
    BioADIResolver,
    BioADIResolverConfig,
    parse_bioadi_output,
    reconstruct_bioadi_predictions,
)
from abrex.resolvers.adapters.learned import (
    LEARNED_SCORER_RESOLVER_VERSION,
    LearnedScorerResolver,
    LearnedScorerResolverConfig,
)
from abrex.resolvers.adapters.schwartz_hearst import (
    SCHWARTZ_HEARST_VERSION,
    SchwartzHearstResolver,
    SchwartzHearstResolverConfig,
)
from abrex.resolvers.base import (
    ExecutionErrorPolicy,
    PredictionDiagnostic,
    PredictionRecord,
    PredictionValidationError,
    PredictionValidationMode,
    PredictionValidationResult,
    Resolver,
    ResolverError,
    ResolverExecutionError,
    ResolverMetadata,
    ResolverRunResult,
    attach_resolver_metadata,
)
from abrex.resolvers.config import (
    ResolverConfig,
    create_resolver_executor,
    resolver_config_from_resolved,
)
from abrex.resolvers.execution import ResolverExecutor
from abrex.resolvers.plod import (
    PLOD_VERSION,
    PlodConfig,
    PlodSpanDetector,
    PlodSpanRecord,
    RawPlodSpan,
    ValidatedPlodSpan,
    serialize_span_record,
)
from abrex.resolvers.plod_pairing import (
    PAIRING_STRATEGIES,
    PAIRING_VERSION,
    PairCandidate,
    PairingResult,
    PatternGreedyPairing,
    PlodPairingConfig,
    PlodPairingResolver,
    PlodPairingResolverConfig,
    PositionAnchoredPairing,
    SpanDetector,
)
from abrex.resolvers.registry import RESOLVERS, register_builtin_components
from abrex.resolvers.serialization import (
    PREDICTION_SCHEMA_VERSION,
    PredictionArtifact,
    PredictionSerializationError,
    fingerprint_prediction_artifact,
    prediction_artifact_from_run,
    prediction_record_from_dict,
    prediction_record_to_dict,
    read_prediction_artifact,
    read_predictions,
    serialize_prediction_artifact,
    serialize_predictions,
    write_prediction_artifact,
    write_predictions,
)
from abrex.resolvers.validation import validate_predictions

__all__ = [
    "ExecutionErrorPolicy",
    "AB3P_ADAPTER_VERSION",
    "BIOADI_ADAPTER_VERSION",
    "AB3P_OFFSET_SCHEMA_VERSION",
    "AB3P_WRAPPER_VERSION",
    "Ab3PCacheConfig",
    "Ab3PInstallationConfig",
    "Ab3PMappingError",
    "Ab3PParseError",
    "Ab3PResolver",
    "BioADIMappingError",
    "BioADIPair",
    "BioADIParseError",
    "BioADIResolver",
    "BioADIResolverConfig",
    "LEARNED_SCORER_RESOLVER_VERSION",
    "LearnedScorerResolver",
    "LearnedScorerResolverConfig",
    "SCHWARTZ_HEARST_VERSION",
    "SchwartzHearstResolver",
    "SchwartzHearstResolverConfig",
    "Ab3PResolverConfig",
    "PREDICTION_SCHEMA_VERSION",
    "PredictionArtifact",
    "PredictionDiagnostic",
    "PredictionRecord",
    "PredictionSerializationError",
    "PredictionValidationError",
    "PredictionValidationMode",
    "ParsedAbbreviation",
    "PredictionValidationResult",
    "RESOLVERS",
    "Resolver",
    "ResolverConfig",
    "ResolverError",
    "ResolverExecutionError",
    "ResolverExecutor",
    "ResolverMetadata",
    "ResolverRunResult",
    "PLOD_VERSION",
    "PlodConfig",
    "PlodSpanDetector",
    "PlodSpanRecord",
    "RawPlodSpan",
    "ValidatedPlodSpan",
    "serialize_span_record",
    "PAIRING_STRATEGIES",
    "PAIRING_VERSION",
    "PairCandidate",
    "PairingResult",
    "PlodPairingConfig",
    "PlodPairingResolver",
    "PlodPairingResolverConfig",
    "PatternGreedyPairing",
    "PositionAnchoredPairing",
    "SpanDetector",
    "attach_resolver_metadata",
    "create_resolver_executor",
    "fingerprint_prediction_artifact",
    "prediction_artifact_from_run",
    "prediction_record_from_dict",
    "prediction_record_to_dict",
    "read_prediction_artifact",
    "read_predictions",
    "register_builtin_components",
    "resolver_config_from_resolved",
    "serialize_prediction_artifact",
    "serialize_predictions",
    "validate_predictions",
    "write_prediction_artifact",
    "write_predictions",
    "build_ab3p_input",
    "parse_ab3p_output",
    "parse_bioadi_output",
    "parse_ab3p_offset_output",
    "reconstruct_offset_predictions",
    "reconstruct_predictions",
    "reconstruct_bioadi_predictions",
]
