"""Offline PubMed/PMC article integration at the resolver boundary."""

from abrex.literature.acquisition import (
    ACQUISITION_SCHEMA_VERSION,
    AcquisitionError,
    AcquisitionEstimate,
    AcquisitionResult,
    LiteratureAcquisitionConfig,
    acquire_pubmed,
    estimate_acquisition,
    load_acquisition_config,
    replay_acquisition,
)
from abrex.literature.corpus_selection import (
    CORPUS_SELECTION_SCHEMA_VERSION,
    CorpusArticleGroup,
    CorpusFrameRecord,
    CorpusSelectionConfig,
    CorpusSelectionError,
    CorpusSelectionResult,
    WorkScaleLimits,
    load_corpus_selection_config,
    select_corpus,
    write_corpus_selection_manifest,
)
from abrex.literature.io import (
    ARTICLE_RESOLUTION_SCHEMA_VERSION,
    ARTICLE_SCHEMA_VERSION,
    ArticleSerializationError,
    article_from_dict,
    article_resolution_to_dict,
    article_to_dict,
    read_article_json,
    serialize_article_resolution,
    write_article_resolution,
)
from abrex.literature.jats import parse_jats_xml, read_jats_xml
from abrex.literature.mapping import (
    ArticleEntity,
    ArticlePredictionRecord,
    ArticleResolutionResult,
)
from abrex.literature.mentions import MentionLink, MentionLinkConfig, link_mentions
from abrex.literature.models import (
    Article,
    ArticleDocument,
    ArticleDocumentProvenance,
    ArticleError,
    ArticleMappingError,
    ArticleSection,
    ArticleSectionLocation,
    ArticleStructure,
)
from abrex.literature.parsers import (
    ArticleParseDiagnostic,
    ArticleParseError,
    ArticleParseResult,
    parse_bioc_json,
    parse_pubmed_xml,
    read_bioc_json,
    read_pubmed_xml,
)
from abrex.literature.registry import SEGMENTERS, register_builtin_components
from abrex.literature.sampling import (
    SAMPLING_SCHEMA_VERSION,
    ArticleGroup,
    FrameRecord,
    SamplingConfig,
    SamplingError,
    SamplingResult,
    SamplingRoleConfig,
    derive_lexicon_view,
    load_sampling_config,
    sample_frame,
    write_sampling_manifest,
)
from abrex.literature.segmenters import (
    ArticleSegmenter,
    ArticleSegmenterConfig,
    SectionDocumentSegmenter,
    SectionSegmenterConfig,
    WholeArticleSegmenter,
)
from abrex.literature.service import (
    ArticleResolutionService,
    LiteratureConfig,
    create_article_resolution_service,
    literature_config_from_resolved,
)

__all__ = [
    "ACQUISITION_SCHEMA_VERSION",
    "ARTICLE_RESOLUTION_SCHEMA_VERSION",
    "ARTICLE_SCHEMA_VERSION",
    "Article",
    "ArticleDocument",
    "ArticleDocumentProvenance",
    "ArticleEntity",
    "ArticleError",
    "ArticleMappingError",
    "ArticleParseDiagnostic",
    "ArticleParseError",
    "ArticleParseResult",
    "ArticlePredictionRecord",
    "ArticleResolutionResult",
    "AcquisitionError",
    "AcquisitionEstimate",
    "AcquisitionResult",
    "ArticleResolutionService",
    "ArticleSection",
    "ArticleSectionLocation",
    "ArticleStructure",
    "MentionLink",
    "MentionLinkConfig",
    "ArticleGroup",
    "ArticleSegmenter",
    "ArticleSegmenterConfig",
    "ArticleSerializationError",
    "CORPUS_SELECTION_SCHEMA_VERSION",
    "CorpusArticleGroup",
    "CorpusFrameRecord",
    "CorpusSelectionConfig",
    "CorpusSelectionError",
    "CorpusSelectionResult",
    "LiteratureConfig",
    "LiteratureAcquisitionConfig",
    "SEGMENTERS",
    "SAMPLING_SCHEMA_VERSION",
    "SamplingConfig",
    "SamplingError",
    "SamplingResult",
    "SamplingRoleConfig",
    "FrameRecord",
    "SectionDocumentSegmenter",
    "SectionSegmenterConfig",
    "WholeArticleSegmenter",
    "article_from_dict",
    "article_resolution_to_dict",
    "article_to_dict",
    "acquire_pubmed",
    "create_article_resolution_service",
    "derive_lexicon_view",
    "estimate_acquisition",
    "load_acquisition_config",
    "link_mentions",
    "load_corpus_selection_config",
    "load_sampling_config",
    "parse_jats_xml",
    "literature_config_from_resolved",
    "parse_bioc_json",
    "parse_pubmed_xml",
    "read_article_json",
    "read_bioc_json",
    "read_jats_xml",
    "read_pubmed_xml",
    "replay_acquisition",
    "register_builtin_components",
    "serialize_article_resolution",
    "write_article_resolution",
    "sample_frame",
    "select_corpus",
    "write_sampling_manifest",
    "write_corpus_selection_manifest",
    "WorkScaleLimits",
]
