"""Capture the installed development environment as a reviewable lock file."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

LOCK_NAME = "requirements-dev.lock"


def main() -> int:
    """Write an exact pip snapshot, excluding this editable checkout."""
    root = Path(__file__).resolve().parents[1]
    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze"],
        cwd=root,
        check=False,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        print(result.stderr, end="", file=sys.stderr)
        return result.returncode

    lines = [
        line
        for line in result.stdout.splitlines()
        if line
        and not line.lower().startswith("abrex @")
        and not line.startswith("-e ")
    ]
    contents = (
        "# Reproducible development snapshot for Python 3.13.\n"
        "# Regenerated by: python scripts/update_dependency_lock.py\n"
        + "\n".join(sorted(lines, key=str.casefold))
        + "\n"
    )
    (root / LOCK_NAME).write_text(contents, encoding="utf-8")
    print(f"Wrote {LOCK_NAME} with {len(lines)} packages.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
