"""Extensible corpus adapters and canonical-record normalization."""

from abrex.corpora.adapters import (
    BioCCorpusAdapter,
    DelimitedPairCorpusAdapter,
    FixtureCorpusAdapter,
    SDUAcronymIdentificationAdapter,
)
from abrex.corpora.base import (
    CorpusAdapter,
    CorpusAdapterError,
    CorpusBuildError,
    CorpusBuildResult,
    CorpusError,
    CorpusPipeline,
    NormalizationPipeline,
    NormalizationStep,
    ParsedSourceAnnotation,
    ParsedSourceRecord,
    SourceResource,
    map_source_record,
)
from abrex.corpora.config import (
    CorpusBuildGroupConfig,
    CorpusBuildGroupsConfig,
    CorpusConfig,
    CorpusOutputConfig,
    SourceResourceConfig,
    corpus_config_from_resolved,
    create_corpus_pipeline,
    load_corpus_build_groups,
)
from abrex.corpora.diagnostics import (
    AdapterDiagnostic,
    DiagnosticsCollector,
    DiagnosticsSummary,
)
from abrex.corpora.normalization import IdentityNormalization, TrimCapturedText
from abrex.corpora.registry import CORPUS_ADAPTERS, NORMALIZERS
from abrex.corpora.serialization import (
    CANONICAL_SCHEMA_VERSION,
    MANIFEST_SCHEMA_VERSION,
    CanonicalSerializationError,
    DatasetManifest,
    build_dataset_manifest,
    fingerprint_file,
    fingerprint_records,
    read_canonical_dataset,
    read_canonical_jsonl,
    read_dataset_manifest,
    record_from_dict,
    record_to_dict,
    serialize_record,
    serialize_records,
    write_canonical_dataset,
    write_canonical_jsonl,
)
from abrex.corpora.validation import (
    CanonicalValidationError,
    CanonicalValidator,
    ValidationAction,
    ValidationIssue,
    ValidationMode,
    ValidationResult,
    ValidationSeverity,
    ValidationSummary,
    validation_issue_from_diagnostic,
)

__all__ = [
    "AdapterDiagnostic",
    "CANONICAL_SCHEMA_VERSION",
    "BioCCorpusAdapter",
    "CanonicalSerializationError",
    "CanonicalValidationError",
    "CanonicalValidator",
    "CorpusAdapter",
    "CorpusAdapterError",
    "CorpusBuildError",
    "CorpusBuildGroupConfig",
    "CorpusBuildGroupsConfig",
    "CorpusBuildResult",
    "CorpusConfig",
    "CorpusError",
    "CorpusOutputConfig",
    "CorpusPipeline",
    "CORPUS_ADAPTERS",
    "DiagnosticsCollector",
    "DiagnosticsSummary",
    "DatasetManifest",
    "DelimitedPairCorpusAdapter",
    "FixtureCorpusAdapter",
    "IdentityNormalization",
    "NORMALIZERS",
    "NormalizationPipeline",
    "NormalizationStep",
    "ParsedSourceAnnotation",
    "ParsedSourceRecord",
    "SourceResource",
    "SourceResourceConfig",
    "SDUAcronymIdentificationAdapter",
    "TrimCapturedText",
    "MANIFEST_SCHEMA_VERSION",
    "ValidationIssue",
    "ValidationAction",
    "ValidationMode",
    "ValidationResult",
    "ValidationSeverity",
    "ValidationSummary",
    "build_dataset_manifest",
    "corpus_config_from_resolved",
    "create_corpus_pipeline",
    "load_corpus_build_groups",
    "fingerprint_file",
    "fingerprint_records",
    "map_source_record",
    "read_canonical_dataset",
    "read_canonical_jsonl",
    "read_dataset_manifest",
    "record_from_dict",
    "record_to_dict",
    "serialize_record",
    "serialize_records",
    "write_canonical_dataset",
    "write_canonical_jsonl",
    "validation_issue_from_diagnostic",
]
